# .github/workflows/hello-world-reusable.yml
name: Reusable Hello World Workflow

on:
  workflow_call:
    inputs:
      name:
        description: 'The name to greet'
        required: true
        default: 'World'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Say Hello
        run: echo "Hello, ${{ inputs.name }}!"
